Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@same'
    'frameworks/kcompletion' : '@same'
    'frameworks/kconfig' : '@same'
    'frameworks/kconfigwidgets' : '@same'
    'frameworks/ki18n' : '@same'
    'frameworks/kwidgetsaddons' : '@same'
    'frameworks/sonnet' : '@same'

Options:
  test-before-installing: True
